### ISSUE TITLE
MongoDB Database Error

### ISSUE THREAD

**Issue by CompeyDev** [nkrasn/g_man#4]
Hi, I was trying to set this up and once it was ready, I ran `python3 gman.py`, everything worked properly until the database errored out. I am not really familiar with python or databases so I was using this project to learn more about them. 

Following is the error:
```
CommandInvokeError("Command raised an exception: ServerSelectionTimeoutError: connection closed,connection closed,connection closed, Timeout: 30s, Topology Description: <TopologyDescription id: 6203608bd32cfd58406f9b51, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('gman-shard-00-00.angzt.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>, <ServerDescription ('gman-shard-00-01.angzt.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>, <ServerDescription ('gman-shard-00-02.angzt.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>]>")
```

**Comment by nkrasn** [comment]
Hi, try going to your database on MongoDB Atlas, click Network Access on the left sidebar, and then add the IP address of the server g_man is running on to the IP access list.

**Comment by CompeyDev** [comment]
I did. It still gives me this same error.

**Comment by nkrasn** [comment]
Hm interesting, does it also happen if you add 0.0.0.0/0 to that list? That should make the database accessible from any IP.

**Comment by CompeyDev** [comment]
Let me try that.

**Comment by CompeyDev** [comment]
Another question: Should the static version of the file be a .tar.xz one or an extracted one?

**Comment by nkrasn** [comment]
Extracted, the executable ffmpeg file should be located in the ffmpeg-static folder you create

**Comment by CompeyDev** [comment]
The executable? I got a tar folder of of the official site. Which when extracted is this:
![image](https://user-images.githubusercontent.com/74418041/153336595-ac5b8e47-e745-4619-9633-6ecb9fcc7ef8.png)

**Comment by nkrasn** [comment]
Almost! Move everything inside the ffmpeg folder into ffmpeg-static and it'll be good.

**Comment by CompeyDev** [comment]
Thanks! It works now :D

**Comment by nkrasn** [comment]
Awesome, glad I could help!
